### ISSUE TITLE
Incorrect example without Tokenization

### ISSUE THREAD

**Issue by zouharvi** [uhh-lt/neural-coref#1]
Hi, thanks for all the great work and making sure that the work is reproducible -- it has made our lives much simpler.

One thing I noticed in the `README.md` example is that the following call:

`http http://127.0.0.1:8080/predictions/<model_name> output_format=raw tokenized_sentences="Die Organisation gab bekannt sie habe Spenden veruntreut."`

Will be interpreted by the model as a sentence with single-character words. This yields the output:

```
HTTP/1.1 200 
Cache-Control: no-cache; no-store, must-revalidate, private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Pragma: no-cache
connection: keep-alive
content-length: 112
x-request-id: 2c148e0d-539b-45a6-8158-a4efa63f4ed7

D i e   O r g a n i s a t i o n   g a b   b e k a n n t   s i e   h a b e   S p e n d e n   v e r u n t r e u t.
```

**Comment by hatzel** [comment]
Good catch, this should be `http http://127.0.0.1:8080/predictions/<model_name> output_format=raw text="Die Organisation gab bekannt sie habe Spenden veruntreut."`. Fixed!
